# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && \
    apt-get install -y libmariadb-dev-compat libmariadb-dev gcc

RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000
EXPOSE 3306

ENV NAME World

# Run app.py when the container launches
CMD ["python", "email_collector.py"]
