version: '3'

services:
  email_collector:
    build:
      context: .
      dockerfile: Dockerfile_email_collector
    image: email_collector_image
    ports:
      - "8000:8000"
    env_file:
      - ./env_file.txt
  
  main:
    build:
      context: .
      dockerfile: Dockerfile_newsletter_sender
    image: main_image
    ports:
      - "4000:4000"
    env_file:
      - ./env_file.txt


